### ISSUE TITLE
diff: /dev/fd/10: No such file or directory

### ISSUE THREAD

**Issue by eserte** [kaz-utashiro/greple-subst#1]
t/01_run.t fails on some FreeBSD system:
```
#   Failed test '--diff'
#   at t/01_run.t line 14.
#                   'diff: /dev/fd/10: No such file or directory
# '
#     doesn't match '(?^u:\A(.*\n){28}\z)'
# Looks like you failed 1 test of 9.
t/01_run.t ...... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/9 subtests 
```
See also: http://matrix.cpantesters.org/?dist=App-Greple-subst%202.2902;os=freebsd;reports=1

**Comment by kaz-utashiro** [comment]
Probably those systems do not have /dev/fd/# access.
I updated the code to check -d /dev/fd or -d /proc/self/fd, but /dev/fd exists.
Again updated to check -r /dev/fd/0 but I'm not sure that works.

**Comment by eserte** [comment]
Just tried some checks using
```
perl -E 'open my $fh, "/" or die $!; opendir my $dirh, "/dev/fd" or die $!; while(defined(my $entry = readdir($dirh))) { say $entry, " -> ", readlink("/dev/fd/$entry") }'
```
On linux systems it works like expected, it lists fd 3 which points to "/"
On freebsd 10 (old, not supported anymore) the files in /dev/fd are not symlinks, but it works (in this case it's fd 4, which is listed)
On newer freebsd systems (12, 13, 14) there are only the fd entries 0, 1 and 2, but nothing else. So checking for /dev/fd/0 does not work here.

**Comment by kaz-utashiro** [comment]
I gave up to make this to work on the system without /dev/fd/ and now test is skipped.  This feature is required when processing data from stdin, and it rarely happens in normal use case.  Thanks for advice.
