### ISSUE TITLE
Test fails with Getopt-Long 2.57

### ISSUE THREAD

**Issue by andk** [kaz-utashiro/greple-subst#3]
Two test reports with the same perl installation. Between the two runs the relevant thing I did was an upgrade from Getopt-Long 2.54 to 2 57:

- pass: http://www.cpantesters.org/cpan/report/ebc35eea-94d7-11ee-8d40-7636fa2b7e3c
- fail: http://www.cpantesters.org/cpan/report/d0746efe-951d-11ee-ac8b-d852c12b7e3c

if I understand correctly, it is a bugfix in Getopt::Long: https://metacpan.org/dist/Getopt-Long/changes

In any case, please take the opportunity to declare the dependency of the tests on Getopt::Long. It would have made the analysis of this case a bit faster. Thanks!

**Comment by kaz-utashiro** [comment]
It was happening by overriding an existing option, so I fixed it.
Getopt::Long@1.39 is indirectly required from Getopt::EX module.
Maybe I should declare Getopt::Long without version.
Thank you!
